[wso2.admin_service.admin]
ADMIN_PORT = 9443

# Sample configurations
[wso2.admin_service.admin.datasourceConfiguration]
description = "APK DB"
url = "jdbc:postgresql://localhost:5432/apkdb"
username = "admin"
password = "admin"
validationTimeout = 30000
testQuery = "SELECT 1"

[wso2.admin_service.admin.throttleConfig]
enableUnlimitedTier = true
