[adapter] 
[adapter.keystore]
  certPath = "$env{APK_HOME}/adapter/cmd/adapter/conf/resources/adapter/security/keystore/mg.pem"
  keyPath = "$env{APK_HOME}/adapter/cmd/adapter/conf/resources/adapter/security/keystore/mg.key"

[adapter.truststore]
  location = "$env{APK_HOME}/adapter/cmd/adapter/conf/resources/adapter/security/truststore"

# Configurations required for configuring the deployment parameters that are used for identifying the Choreo Connect Adapter REST APIs
[adapter.server]
  # Enable/Disable Choreo Connect Adapter REST API
  enabled = true
  # Hostname of the Choreo Connect Adapter
  host = "0.0.0.0"
  # Port of the Choreo Connect Adapter
  port = "9843"
  # Time to live for the Adapter access token
  tokenTTL = "1h"
  # Private key path to use for the token generation
  tokenPrivateKeyPath = "$env{APK_HOME}/adapter/cmd/adapter/conf/resources/adapter/security/keystore/mg.key"
  [[adapter.server.users]]
    username = "admin"
    password = "admin"

[router]
  listenerPort = 9090
  securedListenerPort = 9095
  systemHost = "localhost"
  useRemoteAddress = false

[router.keystore]
  certPath = "/home/wso2/security/keystore/mg.pem"
  keyPath = "/home/wso2/security/keystore/mg.key"

[router.upstream]
[router.upstream.tls]
  trustedCertPath = "/etc/ssl/certs/ca-certificates.crt"
  verifyHostName = true
  disableSslVerification = false

[enforcer]
[enforcer.jwtIssuer]
  enabled = true
  issuer = "https://localhost:9095/testkey"

[enforcer.throttling]
  enableGlobalEventPublishing = true
  jmsConnectionProviderURL = "amqp://admin:$env{tm_admin_pwd}@carbon/carbon?brokerlist='tcp://apim:5673'"
  [enforcer.throttling.publisher]
    username = "admin"
    password = "$env{tm_admin_pwd}"
    [[enforcer.throttling.publisher.URLGroup]]
      receiverURLs = ["tcp://apim:9612"]
      authURLs = ["ssl://apim:9712"]

[enforcer.security]
[[enforcer.security.tokenService]]
  name = "Resident Key Manager"
  issuer = "https://localhost:9444/oauth2/token"
  certificateAlias = "wso2carbon"
  jwksURL = ""
  validateSubscription = false
  consumerKeyClaim = "azp"
  certificateFilePath = "/home/wso2/security/truststore/wso2carbon.pem"

[[enforcer.security.tokenService]]
  name = "MGW"
  issuer = "https://localhost:9095/testkey"
  certificateAlias = "mgw"
  jwksURL = ""
  validateSubscription = false
  consumerKeyClaim = ""
  certificateFilePath = "/home/wso2/security/truststore/mg.pem"

[[enforcer.security.tokenService]]
  name = "APIM Publisher"
  issuer = "https://localhost:9444/publisher"
  validateSubscription = true
  certificateFilePath = "/home/wso2/security/truststore/wso2carbon.pem"

[controlPlane]
  enabled = true
  serviceURL = "https://apim:9444/"
  username = "admin"
  password = "$env{cp_admin_pwd}"
  environmentLabels = ["Default"]
  skipSSLVerification = true
  [controlPlane.brokerConnectionParameters]
    eventListeningEndpoints = ["amqp://admin:$env{cp_admin_pwd}@apim:5673?retries='10'&connectdelay='30'"]

[analytics]
  enabled = false
